### ISSUE TITLE
Modern Yöntemlerle Statik Bir Web Sitesi Yayınlamak

### ISSUE THREAD

**Issue by oguzhankircali** [oguzhankircali/oguzhankircali.github.io#3]
Bilgisayarımızdaki statik bir web sitesinin, bir repository’ye gönderdiğimiz andan başlayan, bir pipeline tarafından dosyaların storage’a kopyalanarak devam ettiği ve ücretsiz SSL’i, güvenlik duvarı olan bir domain üzerinde yayınlanmasına kadar ki bütün sürecinin otomatize edildiğini hayal edelim? Hayal etmekle kalmayıp başlayalım!

1. Bir domain kirala
2. Cloudflare’e bu domain’i kaydet
3. Cloudflare’de domain için SSL ayarla ve sayfa kuralı tanımla
4. Azure’da bir storage açıp statik web sitesi için ayarla
5. Cloudflare’de yönetilen domain için DNS kayıtları ekle
6. Azure’de bir repository oluştur
7. Statik dosyaları Azure Storage’a manuel yükle
8. Repository’den Azure Storage’a kopyalayan bir pipeline hazırla

> Bu aşamalardan domain kiralama hariç hiçbiri için ücret ödememize gerek olmayacaktır. 2020 yılında böyle en azından.

1. Bir domain kirala

GoDaddy’den daha önce aklımda olan bir fikirle ilgili uygun fiyatlı (yıllık ₺63, yıl: 2020) bir domain kiraladım. Daha önce İsim Tescil’den, Natro’dan, Turhost’tan da domain kiraladım. GoDaddy olmasının özel bir sebebi yok bu arada. Cloudflare ile entegrasyon konusunda rahat ederim diye düşünüyordum ki öyle de oldu. Başka bir domain firmasını da rahatlıkla kullanabilirsiniz.

```yml
trigger:
- master
 
pool:
  vmImage: 'windows-latest'
 
steps:
 
- task: AzureFileCopy@2
  inputs:
    SourcePath: '$(Build.SourcesDirectory)'
    azureSubscription: 'Azure subscription 1 (dsdb74er-8uy7-4e1e-py87-sdfsdfsf)'
    Destination: 'AzureBlob'
    storage: 'mystorage'
    containerName: '$web'
```
